### ISSUE TITLE
需要做一些其他路由器系统上的包

### ISSUE THREAD

**Issue by jzmno1** [layerssss/lixian-portal#1]
> 我在路由上跑的，只有python和php，目测是没法用上了。

plan: 
- [ ] openwrt
- [ ] nslu2-linux

**Comment by layerssss** [comment]
路由器上跑nodejs更简单呀，nodejs比php部署简单多了，尝试一下吧小哥

**Comment by jzmno1** [comment]
大哥，在路由上怎么搭建这样的环境，请大哥指点一二。
http://ipkg.nslu2-linux.org/feeds/optware/oleg/cross/stable/
难道要自己编译？

**Comment by jzmno1** [comment]
虽然没法使用大哥写的前端，但是还是非常感激。我用的是tomato。还是乖乖的苦逼的敲命令吧。

**Comment by layerssss** [comment]
@jzmno1  应该是能自己编译的， 编译 nodejs 需要 gcc gcc-c++(有的系统和gcc一起)  openssh(你那个列表里面有) python2.7(在你那个列表里面是 python27 ) 

哎，实在对不起，没有及时回答你的问题，你现在还能尝试一下再你的路由上搭建环境吗？我能帮助你在你的路由器上编译一个nodejs，编译它挺简单的。

**Comment by jzmno1** [comment]
谢谢大大能关注我的问题，如果大大能把这个前端集成到openwrt或者tomato之类的，真是小白之福，不懂怎么交叉编译，曾经尝试过结果没成功。现在玩玩第三方路由固件的人挺多的，以后玩的人多了在前端做个推广小广告也是不错的。希望大大能编译下tomato下的nodejs，如果能出教程就更好了，比较nodejs大部分人不懂，不然这样的好系统只能你们高手玩了，小白们只能哭b的敲命令了。

**Comment by jzmno1** [comment]
如果能打包一个optware包，绝对能迅速推广。
ipkg install git
cd /root
git clone https://github.com/joyent/node.git
cd node
./configure --prefix=/opt/node
make
make install
然后提示 
  cc '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D_GNU_SOURCE' '-DHAVE_CONFIG_H' -I../deps/uv/include -I../deps/uv/src  -pthread -pthread -Wall -Wextra -Wno-unused-parameter -g --std=gnu89 -pedantic -Wall -Wextra -Wno-unused-parameter -Wstrict-aliasing -O3 -ffunction-sections -fdata-sections -fno-tree-vrp -fno-tree-sink  -MMD -MF /opt/root/node/out/Release/.deps//opt/root/node/out/Release/obj.target/libuv/deps/uv/src/unix/core.o.d.raw  -c -o /opt/root/node/out/Release/obj.target/libuv/deps/uv/src/unix/core.o ../deps/uv/src/unix/core.c
  cc '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D_GNU_SOURCE' '-DHAVE_CONFIG_H' -I../deps/uv/include -I../deps/uv/src  -pthread -pthread -Wall -Wextra -Wno-unused-parameter -g --std=gnu89 -pedantic -Wall -Wextra -Wno-unused-parameter -Wstrict-aliasing -O3 -ffunction-sections -fdata-sections -fno-tree-vrp -fno-tree-sink  -MMD -MF /opt/root/node/out/Release/.deps//opt/root/node/out/Release/obj.target/libuv/deps/uv/src/unix/dl.o.d.raw  -c -o /opt/root/node/out/Release/obj.target/libuv/deps/uv/src/unix/dl.o ../deps/uv/src/unix/dl.c
  cc '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D_GNU_SOURCE' '-DHAVE_CONFIG_H' -I../deps/uv/include -I../deps/uv/src  -pthread -pthread -Wall -Wextra -Wno-unused-parameter -g --std=gnu89 -pedantic -Wall -Wextra -Wno-unused-parameter -Wstrict-aliasing -O3 -ffunction-sections -fdata-sections -fno-tree-vrp -fno-tree-sink  -MMD -MF /opt/root/node/out/Release/.deps//opt/root/node/out/Release/obj.target/libuv/deps/uv/src/unix/fs.o.d.raw  -c -o /opt/root/node/out/Release/obj.target/libuv/deps/uv/src/unix/fs.o ../deps/uv/src/unix/fs.c
../deps/uv/src/unix/fs.c: In function 'uv__to_stat':
../deps/uv/src/unix/fs.c:532: error: 'struct stat' has no member named 'st_atim'
../deps/uv/src/unix/fs.c:533: error: 'struct stat' has no member named 'st_atim'
../deps/uv/src/unix/fs.c:534: error: 'struct stat' has no member named 'st_mtim'
../deps/uv/src/unix/fs.c:535: error: 'struct stat' has no member named 'st_mtim'
../deps/uv/src/unix/fs.c:536: error: 'struct stat' has no member named 'st_ctim'
../deps/uv/src/unix/fs.c:537: error: 'struct stat' has no member named 'st_ctim'
../deps/uv/src/unix/fs.c:547: error: 'struct stat' has no member named 'st_ctim'
../deps/uv/src/unix/fs.c:548: error: 'struct stat' has no member named 'st_ctim'
make[1]: **\* [/opt/root/node/out/Release/obj.target/libuv/deps/uv/src/unix/fs.o] Error 1
make[1]: Leaving directory `/opt/root/node/out'
make: **\* [node] Error 2
在高清机里尝试了，搞了一天才编译好，还是不知道用。也不知道不知道怎么打包ipk文件。
对我等小白来说太难了。

**Comment by layerssss** [comment]
求推荐一款可刷第三方固件的路由

**Comment by jzmno1** [comment]
大哥，多了去了hg320就可以刷tomato，60块。openwrt就更多了。希望大大支持下optware。

**Comment by layerssss** [comment]
俺这两天正好树莓派坏了，整个路由器来用，顺便研究研究看能不能把这货打一个包

**Comment by jzmno1** [comment]
optware很好打包的，所有软件都装在opt目录，tar打包就可以了。就玩的角度我推荐hg320.rg200e-ca。淘宝一把，二手的60块的样子，新的100块。玩高端一点就玩腾达1800吧。不过我还是推荐高清机。mips和arm构架的cpu都支持optware.如果需要我可以把我的opt打包给你。
关键不知道交叉编译软件，只会用被人编译好的。

**Comment by layerssss** [comment]
@jzmno1 感谢！坐等几天吧，下个星期我正好搬家，搬到新家里就换上新的路由

**Comment by jzmno1** [comment]
期待大大给我等小白带来好消息。秒杀群辉写的那个。

**Comment by tellok** [comment]
同求  T。T

**Comment by layerssss** [comment]
@latel 你的路由器用的什么系统？

**Comment by tellok** [comment]
木有买能刷系统的路由啊。FAST自带

**Comment by ghost** [comment]
交叉编译成功了 https://github.com/netzhi/my_openwrt_mod/tree/master/package/nodejs 
改的别人的脚本

**Comment by layerssss** [comment]
@netzhi :+1: nice! 可以给 ravageralpha 提一个 Pull-Request ，这样更多的用户就能用到你加的包了 

![image](https://f.cloud.github.com/assets/1559832/1518510/0fa77d2a-4b3a-11e3-9684-6d454e22fafc.png)

![image](https://f.cloud.github.com/assets/1559832/1518512/1ba9f15c-4b3a-11e3-8c29-464a9b6be116.png)

![image](https://f.cloud.github.com/assets/1559832/1518522/6a4815f0-4b3a-11e3-99ea-dd6d9db9ddac.png)

**Comment by manecocomph** [comment]
有没有详细的教程，怎么才能使用你编译的nodejs 在tomota 上安装， 谢谢

**Comment by layerssss** [comment]
@manecocomph  :crying_cat_face:  暂时没有办法，不过，俺会想办法的；可能会做一个不需要下载，只用系统提供的 bash 来运行的客户端，有进展了会通知你们的，注意邮件。

**Comment by soonco** [comment]
@netzhi 请问怎么编译nodejs到路由器上？作为前端工程师来说js要是能搞到路由上最牛x~

**Comment by layerssss** [comment]
现在程序性能要求比较高了，不再可能运行到路由器上了，所以这个 issue 暂时关掉
