### ISSUE TITLE
启动后报错

### ISSUE THREAD

**Issue by gowinder** [layerssss/lixian-portal#14]
login
    raise NotImplementedError('user is not logged in')

然后用浏览器打开，要输入用户名密码，是输入迅雷的吗？
我输入了，可是提示我要我输入EMAIL名称

**Comment by layerssss** [comment]
@gowinder 是的，是迅雷的离线下载账户的， 因为迅雷的离线下载用户名便是 email 地址，你的不是吗？

**Comment by gowinder** [comment]
啊？我一直用我的迅雷账号登录啊，就是个用户名，而且，我在WINDOWS下面可以直接用VIP的子账号登录xulei_lixian没有问题

**Comment by gowinder** [comment]
我试过用EMAIL登录了，出现 操作失败⋯⋯

**Comment by gowinder** [comment]
是直接运行 node lixian-partal的根目录吧？
我运行后报错：
 node lixian-portal-master
portal ready on http://127.0.0.1:3000/
Command failed: Traceback (most recent call last):
  File "/home/go/app/lixian-portal-master/xunlei-lixian/lixian_cli.py", line 63, in <module>
    execute_command()
  File "/home/go/app/lixian-portal-master/xunlei-lixian/lixian_cli.py", line 60, in execute_command
    commands[command](args[1:])
  File "/home/go/app/lixian-portal-master/xunlei-lixian/lixian_cli_parser.py", line 165, in parse
    return f(parser(args_list, _args, *_kwargs))
  File "/home/go/app/lixian-portal-master/xunlei-lixian/lixian_commands/list.py", line 38, in list_task
    client = create_client(args)
  File "/home/go/app/lixian-portal-master/xunlei-lixian/lixian_commands/util.py", line 53, in create_client
    return XunleiClient(args.username, args.password, args.cookies)
  File "/home/go/app/lixian-portal-master/xunlei-lixian/lixian.py", line 69, in **init**
    self.login()
  File "/home/go/app/lixian-portal-master/xunlei-lixian/lixian.py", line 195, in login
    raise NotImplementedError('user is not logged in')
NotImplementedError: user is not logged in

**Comment by gowinder** [comment]
我又去迅雷离线官网页面看了下，是用用户名登录啊。

**Comment by gowinder** [comment]
请问下怎么解决哦。
我有个机器专门装了XP下载，不过是ATOM的U，以前还好，现在迅雷客户端太狠了，一开就100%占用CPU，实在是不想用了。

**Comment by layerssss** [comment]
@gowinder  俺刚刚更改了一下（现在可以用用户名登录了），你可以试试重新下载最新的版本然后再登录试试。

出现你贴出来的那一堆错误日志是正常的，因为你刚开始运行它还没有登录。，如果你登录时提示这个，就是用户名密码错了登录失败。

**Comment by gowinder** [comment]
好的，我试试，谢谢啊

**Comment by gowinder** [comment]
第一可以登录了，然后我加了一个ED2K地址下载，结果没加进去，然后我把NODE关了，重新打开，再登录就进不去了，浏览器一直卡着，node那边显示
node lixian-portal-master
portal ready on http://127.0.0.1:3000/
undefined
undefined

undefined

**Comment by layerssss** [comment]
node 当然要一直开着，

**Comment by gowinder** [comment]
是开着啊，但只要我在浏览器操作就显示undefined，而且浏览器那边老卡着。

**Comment by layerssss** [comment]
不是卡着是正在登录，等着， 不用管 node 这边显示什么

**Comment by gowinder** [comment]
增加任务后一直显示：
正进行任务，刷新任务列表

**Comment by layerssss** [comment]
@gowinder  那说明你登录成功了，（并且增加下载也成功了, 它正在下载） 过一会儿来刷新一下就可看到它正在下载了

**Comment by layerssss** [comment]
node 进程别关

**Comment by gowinder** [comment]
没关，等半个小时，还是一样，正在取得任务

**Comment by layerssss** [comment]
刷新一下，界面是个网页，它不会自动刷新的（看来确实需要自动刷新了）

**Comment by layerssss** [comment]
@gowinder 应该是能用了吧，那我先把这个issue 关了，有问题你再告诉我啦
