### ISSUE TITLE
运行没有效果

### ISSUE THREAD

**Issue by Mr-Zack** [layerssss/lixian-portal#15]
这是我在 Raspberry PI 上运行:
pi@raspberrypi ~/src/lixian-portal $ pwd
/home/pi/src/lixian-portal
pi@raspberrypi ~/src/lixian-portal $ node ./bin/lixian-portal
pi@raspberrypi ~/src/lixian-portal $ 

然后到浏览器  
http://localhost:3000/login
找不到页面

**Comment by layerssss** [comment]
可能你的 nodejs 安装有问题吧（只是猜测）？你 `node --version` 看一下输出结果是什么？

**Comment by layerssss** [comment]
@Mr-Zack  sorry for the late reply

**Comment by Mr-Zack** [comment]
pi@raspberrypi ~ $ node --version
pi@raspberrypi ~ $
pi@raspberrypi ~ $ nodejs --version
v0.6.19
pi@raspberrypi ~ $

THX~~~

**Comment by Mr-Zack** [comment]
THX for your
哦可以了。
用 nodejs 才行。。
好像有个不足地方，登录后就自动下载整个离线列表。

**Comment by layerssss** [comment]
@Mr-Zack  不客气。

登录后自动下载想是方便用户吧，不用你再操作，因为反正你添加了任务进来也都是要下载的。

而且，这个离线取回是单线程的，基本上不会影响玩游戏上网的网速（如果开网页，会把它的速度挤开），所以也不用担心占网速啦
