### ISSUE TITLE
添加 aria2 rpc 下载

### ISSUE THREAD

**Issue by Fantoccini** [layerssss/lixian-portal#16]
https://github.com/sonnyp/aria2.js
迅雷离线任务完成后，将任务通过 rpc 提交给在后台运行的 aria2 daemon 后返回，由 aria2 继续下载。

**Comment by layerssss** [comment]
:+1: 好主意

**Comment by layerssss** [comment]
目前用 request 做单线程下载还是比较稳定的，而且连接迅雷的服务器没必要用更复杂的下载方式，这个 issue 暂时关了
