### ISSUE TITLE
这软件在raspberrypi上具体怎么用？

### ISSUE THREAD

**Issue by linux0ne** [layerssss/lixian-portal#17]
RT!
我家里有一个rpi，在rpi上我安装了iambus的离线迅雷脚本，为了实现用rpi挂硬盘下载然后用samba共享，我还需要做什么 ？    能不能具体讲一下。

**Comment by layerssss** [comment]
你需要想办法在 rpi 上安装 nodejs，然后就可以运行它了，至于怎么安装 nodejs 我就帮不了你了，不同系统不一样，安装好了后可以按照说明运行它

**Comment by linux0ne** [comment]
安装nodejs?   这个纯粹是为了你这个软件服务的吧？  我莫不如直接用离线脚本，然后再安装上samba，然后再用脚本将下载下来的文件直接放到samba的共享文件夹里，最后自由访问得了。呵呵

主要是nodejs这个东西我没有弄过，实在不知道如何弄，在网上很多内容，说法不一，没有时间去伪存真。

**Comment by layerssss** [comment]
是的
