### ISSUE TITLE
帐号问题

### ISSUE THREAD

**Issue by sicode** [layerssss/lixian-portal#18]
在登录页面那里输入的是迅雷帐号的吧？如果是，那登录后提示“unhandled vcode”是什么意思呢？

**Comment by sicode** [comment]
還有個提示“waiting for selector timeout: #rowbox_list”

**Comment by layerssss** [comment]
@sicode 显示“unhandled vcode”提示是因为你安装的代码版本还没包括输入验证码功能，这个功能两周前才刚刚完成，但是忘记发布了，我刚刚发布它，所以你更新一下代码（`npm update lixian-portal`）后应该就不会再出现这个提示——而是提示你输入验证码了。

另外 “waiting for selector timeout....” 这个问题偶尔会出现，但是还没找到其原因，遇到时重试一下就好。

**Comment by sicode** [comment]
还是会提示相同错误......
“waiting for”的错误估计是非会员登录，我用会员登录很少出现，用非会员几乎100%出现

**Comment by sicode** [comment]
更新后，输入验证码那框一直弹出来，而且一次过跳2个出来（不知道是不是），每次都是相同的验证码。

**Comment by layerssss** [comment]
非会员应该是不能登录的啦

**Comment by sicode** [comment]
那驗證碼問題呢？

**Comment by layerssss** [comment]
现在还不是很稳定，登录时重复要求输入验证码的情况偶尔会出现，你暂时把程序重启一下重试就好

Kind regards,

Michael Yin

在 2014年10月13日，下午1:08，sicode notifications@github.com 写道：

**Comment by sicode** [comment]
終於進去了.......總結下
頁面一直在請求vcode頁面，從不間斷，即使我還沒登錄或者已經登錄。
第一次彈驗證碼輸入完以後還會彈的解決方法是，除了第一次輸入外，只要驗證碼不變其他的都直接點確定，然後就進去了。
不會截圖上傳到這裡
這個應該支持ED2K的吧？

**Comment by layerssss** [comment]
支持 ed2k 的（还支持磁力链接、“thunder://”链接）

Kind regards,

Michael Yin

在 2014年10月13日，下午3:52，sicode notifications@github.com 写道：

**Comment by sicode** [comment]
期待能完全解決驗證碼問題

**Comment by layerssss** [comment]
@sicode 我重新开了一个 issue #19 你可以点下图中的 subscribe 按钮关注这个 issue ，这样修复时你会得到通知 

![image](https://cloud.githubusercontent.com/assets/1559832/4610592/8aacb3b2-52b1-11e4-82e4-9a05773c4903.png)

btw. 截图后直接在文本编辑框里点 Ctrl + V （粘贴）即可贴图。

**Comment by sicode** [comment]
OK，長期關注進度....
