### ISSUE TITLE
某些时候重复地弹出输入验证码对话框

### ISSUE THREAD

**Issue by layerssss** [layerssss/lixian-portal#19]
这应该是因为有很多错误情况没有处理，比如密码错误，或者网络错误、网络延时等。

在这个问题修复之前的临时解决办法：

> 第一次彈驗證碼輸入完以後還會彈的解決方法是，除了第一次輸入外，只要驗證碼不變其他的都直接點確定，然後就進去了。 由 @sicode 整理

**Comment by layerssss** [comment]
@sicode 这个问题在最近解决了，而且最新的 0.2.14 增加了许多改进，还支持在移动设备上直接查看格式兼容的视频图片等，give it a try!

**Comment by sicode** [comment]
重新下載一次就可以了吧？

**Comment by layerssss** [comment]
建议你用 npm 安装（npm install lixian-portal -g），如果你之前就是用 npm 安装了的话，就 npm update lixian-portal -g 就可以升级了

**Comment by sicode** [comment]
![013](https://cloud.githubusercontent.com/assets/3986116/4862080/2b8aaf2c-6109-11e4-9412-0407bb42a96b.png)

phantomjs 版本为1.9.8

不知道为什么，虽然提示出错，但过一阵子又会自动启动任务，大概这个错误没那么严重

**Comment by sicode** [comment]
顺带说下，新版好高端.....比之前好很多

**Comment by sicode** [comment]
![image](https://cloud.githubusercontent.com/assets/3986116/4862391/268a529a-610c-11e4-8025-613c1f8a45a6.png)
删除任务一定机率会出错

添加任务一定机率出错

登录了以后很容易就会出现刷新列表失败或者提示登录失败，不知道是不是网络问题

**Comment by layerssss** [comment]
我增加了一个额外的 issue #20 来记录这个问题

**Comment by sicode** [comment]
更新後登錄登不進去..........
![004](https://cloud.githubusercontent.com/assets/3986116/4963427/2e8e132e-6755-11e4-8d12-18642cd3c042.png)

**Comment by sicode** [comment]
不知道你會不會覺得我很煩？

**Comment by layerssss** [comment]
不会不会 @sicode ，这些问题是要尽量发现并解决的。

**Comment by layerssss** [comment]
虽然我自己也在用，但是有的问题偶尔才出现，所以得收集你们的反馈， 我仔细检查一下。

**Comment by sicode** [comment]
那行，這樣我就可以放心提錯誤了

**Comment by sicode** [comment]
看到有評論問怎麼在樹莓派上運行，這個我也試過，主要還是卡在phantomjs上，樹莓派的處理是arm，網上也找到一些arm版的phantomjs，不知道是不是我安裝方法有問題.......僅僅是試下，拿樹莓派下載還不如拿PC機下載省心，折騰除外......

**Comment by layerssss** [comment]
最新的版本 （0.3.x 以上 ）不需要 phantomjs 了

**Comment by sicode** [comment]
有空再試試

**Comment by sicode** [comment]
![image](https://cloud.githubusercontent.com/assets/3986116/6124066/f9f6f7c2-b144-11e4-8ea5-6a828cd10b87.png)
在樹莓派上安裝提示這個錯誤
