### ISSUE TITLE
No compatible version found: iced-coffee-script@'>=1.4.0c <1.5.0-'

### ISSUE THREAD

**Issue by shiny** [layerssss/lixian-portal#2]
npm ERR! message No compatible version found: iced-coffee-script@'>=1.4.0c <1.5.0-'
npm ERR! message Valid install targets:
npm ERR! message ["1.2.0-c","1.2.0-d","1.2.0-e","1.2.0-f","1.2.0-g","1.2.0-h","1.2.0-i","1.2.0-j","1.2.0-k","1.2.0-l","1.2.0-m","1.2.0-n","1.2.0-o","1.2.0-p","1.2.0-q","1.2.0-r","1.2.0-s","1.2.0-t","1.2.0-u","1.3.1-a","1.3.1-b","1.3.1-c","1.3.3-a","1.3.3-b","1.3.3-c","1.3.3-d","1.3.3-e","1.3.3-f","1.3.3-g","1.3.3-h","1.4.0-a","1.4.0-b","1.4.0-c"]

是在我的小树莓派上跑的 node 版本

**Comment by layerssss** [comment]
jis，sorry。明早起来九点钟之前修正，今天回来好累，先洗洗睡了；。ps. 上海的水上公园都好坑不要去

**Comment by shiny** [comment]
幸苦啦~

PS: 突然发现这个 IcedCoffeeScript 看上去很简洁，我也去看看。

**Comment by layerssss** [comment]
@shiny  :+1:  搞定

**Comment by layerssss** [comment]
顺便更新了 xunlei-lixian

**Comment by shiny** [comment]
@layerssss 现在报的错是如下：
npm ERR! message No compatible version found: iced-coffee-script@'>1.4.0'
npm ERR! message Valid install targets:
npm ERR! message ["1.2.0-c","1.2.0-d","1.2.0-e","1.2.0-f","1.2.0-g","1.2.0-h","1.2.0-i","1.2.0-j","1.2.0-k","1.2.0-l","1.2.0-m","1.2.0-n","1.2.0-o","1.2.0-p","1.2.0-q","1.2.0-r","1.2.0-s","1.2.0-t","1.2.0-u","1.3.1-a","1.3.1-b","1.3.1-c","1.3.3-a","1.3.3-b","1.3.3-c","1.3.3-d","1.3.3-e","1.3.3-f","1.3.3-g","1.3.3-h","1.4.0-a","1.4.0-b","1.4.0-c"]

**Comment by layerssss** [comment]
你的nodejs版本号是多少？（node --version)

**Comment by shiny** [comment]
root@QianTang:~# node --version
v0.10.12
root@QianTang:~# npm --version
1.1.4

**Comment by layerssss** [comment]
那确实是因为npm版本太旧了，1.1.3是去年年初的版本了[https://github.com/isaacs/npm/commit/0942078e6bfe7ea9941931cc5b012a1605ad4cf4](https://github.com/isaacs/npm/commit/0942078e6bfe7ea9941931cc5b012a1605ad4cf4) ，试下使用`(sudo) npm update -g` 升级一下npm 本身，再安装

**Comment by layerssss** [comment]
@shiny 试一下吧 :8ball:

**Comment by shiny** [comment]
我用树莓派自带的 apt-get install npm 升级最大版本也就是 1.1.4 。所以刚刚重新下载编译了份（树莓派上编译，足足让我睡了觉才编译好），再安装就成了。

谢谢你的帮助！

**Comment by layerssss** [comment]
@shiny 不客气，看来npm版本也得注意呀
