### ISSUE TITLE
删除任务时有一定机率会出错

### ISSUE THREAD

**Issue by layerssss** [layerssss/lixian-portal#20]
![https://cloud.githubusercontent.com/assets/3986116/4862391/268a529a-610c-11e4-8025-613c1f8a45a6.png](https://cloud.githubusercontent.com/assets/3986116/4862391/268a529a-610c-11e4-8025-613c1f8a45a6.png)

**Comment by alphatok** [comment]
也遇到过，怎么解决的

**Comment by layerssss** [comment]
@igoogll 现在还没找到问题的原因，暂时只能重试一下失败的操作。

**Comment by layerssss** [comment]
@igoogll 找到问题了，现在解决为显示操作失败了（而非整个程序崩溃），可以 npm update lixian-portal 升级一下程序
