### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by layerssss** [layerssss/lixian-portal#21]
![004](https://cloud.githubusercontent.com/assets/3986116/4963427/2e8e132e-6755-11e4-8d12-18642cd3c042.png)

**Comment by layerssss** [comment]
@sicode 你能看一下版本号是多少吗？  `npm ls -g lixian-portal`

**Comment by sicode** [comment]
0.3.5

**Comment by sicode** [comment]
還有個
現在程序在ubuntu下跑，會自動建立與任務對應的文件夾，任務的文件結構也不需要建立文件夾。
每個任務都建立一個獨立文件夾存放，如果下載的是BT任務，那路徑就有點深了。
有空補上截圖

**Comment by layerssss** [comment]
@sicode 还没发布，我把几个问题解决后再一起发布再通知你

**Comment by sicode** [comment]
好的....准备双11，打算搞台NAS玩玩
