### ISSUE TITLE
0.3.10版本无法登录

### ISSUE THREAD

**Issue by sicode** [layerssss/lixian-portal#23]
![image](https://cloud.githubusercontent.com/assets/3986116/4995119/82454fae-69f9-11e4-99fe-1a2db5746ed6.png)
现在是100%登录失败......

目前已知的情况：
1. 需要登录输入验证码的帐号会出现这个问题

**Comment by layerssss** [comment]
你的网络环境需要代理服务器吗？

**Comment by sicode** [comment]
代理服务器？我的是美国VPS，独立IP

**Comment by layerssss** [comment]
原来是这样！这个是因为迅雷上市禁掉了国外的ip所以产生这个错误，你下载应该用家里的计算机（或者 NAS 或者树莓派）下载嘛，然后才可以通过局域网共享快速访问才对。

**Comment by layerssss** [comment]
我家里用的是一台这个机器 http://www.amazon.cn/gp/product/B00KG0PY14/ref=wms_ohs_product?ie=UTF8&psc=1 ，在上面安装了 centos 跑的。

**Comment by layerssss** [comment]
之前用过一段时间树莓派 + 移动硬盘，但是后来树莓派坏了，就扔了。

**Comment by sicode** [comment]
这机器应该能跑ubuntu吧？

**Comment by layerssss** [comment]
绰绰有余

**Comment by sicode** [comment]
刚刚试了下通过VPS代理登录lixian.xunlei.com，正常没问题。

**Comment by sicode** [comment]
![image](https://cloud.githubusercontent.com/assets/3986116/5010803/d9cb05c6-6ab1-11e4-9571-34f06337574e.png)
虚拟机里装了下，安装过程很顺利，启动时提示找不到此目录，ls看了下，是有的

**Comment by layerssss** [comment]
which node 看一下结果

**Comment by sicode** [comment]
沒有任何返回內容，在安裝npm的時候看到有安裝node相關內容，那是不是需要獨立安裝node一遍？
我記得當時在VPS上配置也沒這麼難

**Comment by layerssss** [comment]
对了你是不是 ubuntu？

**Comment by layerssss** [comment]
我想起来 ubuntu 的 nodejs 命令不是 node, 是 nodejs， node 是另外一个程序，你先用 apt-get 升级一下 nodejs ，我去看看我有没有记错。

**Comment by layerssss** [comment]
@sicode 我刚刚做了一个小更新，你升级到 0.3.11 版本再试一下

**Comment by sicode** [comment]
正是ubuntu。。。。。。

**Comment by layerssss** [comment]
@sicode 你升级到 0.3.11 版本再试一下

**Comment by sicode** [comment]
VPS配置：ubuntu 14.04 內核2.6.32，運行which node 正常返回路徑
本地虛擬機：ubuntu 14.04 內核3.13.0，運行which node 沒有任何返回內容

**Comment by sicode** [comment]
成功運行了
那如果我想退出的話，直接按ctrl+z(ctrl+c)?
這樣會導致監聽端口不能釋放掉，下次啟動就得先把nodejs進程結束掉，才能正常啟動。
本地登錄帳號還是提示“操作失敗”，跟我的截圖上的一樣

**Comment by sicode** [comment]
ctrl+c是可以連帶監聽端口也釋放掉，不好意思，坑了

**Comment by layerssss** [comment]
Hi @sicode 我更新了一个版本 0.3.13 , 虽然没有修复登录失败这个问题，但是增加了记录详细过程的功能，麻烦你再试着登录一下，遇到失败时（在出错提示那个界面），点“查看详细日志”按钮，然后把页面下面出现的东西复制到电子邮件里给我吧，我的邮箱是 layerssss@gmail.com

**Comment by layerssss** [comment]
@sicode 这个问题终于修复了，感谢帮助，我之前一直发现不了这个问题，后来发现是因为我自己服务器上用了代理服务器，代理把请求矫正地更加严格才通过迅雷的检查，切换成直接连接才发现这个问题。你升级一下再试试。

**Comment by sicode** [comment]
那問題來了......哪家代理服務器強

**Comment by layerssss** [comment]
@sicode 不是翻墙用的代理，是我家里自己用的缓存代理，没多大用途，不过感觉习惯一些。

**Comment by layerssss** [comment]
@sicode 不过如果你家里网络环境比较好的话，用云梯挺不错的

**Comment by sicode** [comment]
那緩存代理跟本機緩存有什麼區別？
出國一般聯通比較好，親測......

**Comment by layerssss** [comment]
实质没什么区别，只不过是放在家里的服务器上，家里的所有设备都可以共享缓存，比如室友的电脑，，如果在人比较多的地方，比如办公室里效果就明显了。

**Comment by sicode** [comment]
原來如此
