### ISSUE TITLE
能否写下在树莓派的安装方法呢？

### ISSUE THREAD

**Issue by Dakai** [layerssss/lixian-portal#3]
我尝试着自己安装，安装好了xunlei-lixian,安装好了nodejs,
到了sudo npm install lixian-portal -g这一步出了很多ERR，能否指点一下，谢谢！

**Comment by layerssss** [comment]
把产生的错误复制过来看一看吧？

**Comment by layerssss** [comment]
@Dakai 否则俺没法判断出错原因呀

**Comment by Dakai** [comment]
好的，多谢
pi@raspbmc:~$ sudo npm install lixian-portal -g
npm http GET https://registry.npmjs.org/lixian-portal
npm http GET https://registry.npmjs.org/iced-coffee-script
npm http GET https://registry.npmjs.org/lazy
npm http GET https://registry.npmjs.org/express
npm http GET https://registry.npmjs.org/jade
npm http 304 https://registry.npmjs.org/lazy
npm http GET https://registry.npmjs.org/lazy/-/lazy-1.0.11.tgz
npm http 304 https://registry.npmjs.org/iced-coffee-script
npm ERR! error installing lixian-portal@0.0.22

npm ERR! Error: No compatible version found: iced-coffee-script@'>1.4.0'
npm ERR! Valid install targets:
npm ERR! ["1.2.0-c","1.2.0-d","1.2.0-e","1.2.0-f","1.2.0-g","1.2.0-h","1.2.0-i","1.2.0-j","1.2.0-k","1.2.0-l","1.2.0-m","1.2.0-n","1.2.0-o","1.2.0-p","1.2.0-q","1.2.0-r","1.2.0-s","1.2.0-t","1.2.0-u","1.3.1-a","1.3.1-b","1.3.1-c","1.3.3-a","1.3.3-b","1.3.3-c","1.3.3-d","1.3.3-e","1.3.3-f","1.3.3-g","1.3.3-h","1.4.0-a","1.4.0-b","1.4.0-c"]
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:488:10)
npm ERR!     at next_ (/usr/share/npm/lib/cache.js:438:17)
npm ERR!     at next (/usr/share/npm/lib/cache.js:415:44)
npm ERR!     at /usr/share/npm/lib/cache.js:408:5
npm ERR!     at saved (/usr/share/npm/lib/utils/npm-registry-client/get.js:147:7)
npm ERR!     at Object.oncomplete (/usr/lib/nodejs/graceful-fs.js:230:7)
npm ERR! You may report this log at:
npm ERR!     http://bugs.debian.org/npm
npm ERR! or use
npm ERR!     reportbug --attach /home/pi/npm-debug.log npm
npm ERR!
npm ERR! System Linux 3.6.11
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "lixian-portal" "-g"
npm ERR! cwd /home/pi
npm ERR! node -v v0.6.19
npm ERR! npm -v 1.1.4
npm ERR! message No compatible version found: iced-coffee-script@'>1.4.0'
npm ERR! message Valid install targets:
npm ERR! message ["1.2.0-c","1.2.0-d","1.2.0-e","1.2.0-f","1.2.0-g","1.2.0-h","1.2.0-i","1.2.0-j","1.2.0-k","1.2.0-l","1.2.0-m","1.2.0-n","1.2.0-o","1.2.0-p","1.2.0-q","1.2.0-r","1.2.0-s","1.2.0-t","1.2.0-u","1.3.1-a","1.3.1-b","1.3.1-c","1.3.3-a","1.3.3-b","1.3.3-c","1.3.3-d","1.3.3-e","1.3.3-f","1.3.3-g","1.3.3-h","1.4.0-a","1.4.0-b","1.4.0-c"]
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/npm-debug.log
npm not ok

需要把Log内容也帖上来吗？

**Comment by layerssss** [comment]
试着先执行一遍

```
sudo npm update -g
```

然后再执行

```
sudo npm install lixian-portal -g
```

试试

**Comment by Dakai** [comment]
谢谢，但是还是不行，貌似是 No compatible version found: iced-coffee-script@'>1.4.0' 这个问题
我试着单独安装iced-coffee-script 1.4.0c，没有报错，但是再试还是一样的错误信息

**Comment by layerssss** [comment]
看来你也得重新编译并安装一遍nodejs了

**Comment by layerssss** [comment]
快速编译安装nodejs

```
curl http://nodejs.org/dist/v0.10.15/node-v0.10.15.tar.gz | tar xz
cd node-v0.10.15 && make && make install
cd .. && rm -Rf node-v0.10.15
```

**Comment by layerssss** [comment]
试一试看，，安装前得确认一下python的版本号，需要`python --version` 2.7~ 2.9

**Comment by Dakai** [comment]
-,- 正在编译中，居然提示没有C编译环境，树莓派不是有C环境的吗，难道Raspbmc阉割掉了，安装了gcc编译中

**Comment by Dakai** [comment]
编译完了，再安装portal还是一样的问题

**Comment by layerssss** [comment]
你看一下npm的版本（通过`npm --version`命令）

**Comment by Dakai** [comment]
好的，是1.1.4

**Comment by layerssss** [comment]
那不对呀，那应该还没有安装上新的nodejs, 使用`make`命令编译完`nodejs`之后，还要使用`make install`命令（以**sudo**运行）安装它到系统中去

**Comment by layerssss** [comment]
如果安装成功之后，npm --version 的值应该是 1.3.x左右， 如果make install 成功后，版本依然未变，则可能系统自带的优先级更改，请先用`which npm -a && which node -a`命令查看一下所有的安装位置

**Comment by Dakai** [comment]
which npm -a
得到的结果是/usr/bin/npm
which node -a 
没任何结果

**Comment by layerssss** [comment]
那你nodejs 安装了吗？

**Comment by Dakai** [comment]
之前用的sudo apt-get install nodejs 安装过，然后又编译过一次，再输入sudo apt-get install nodejs显示已安装最新版本

**Comment by layerssss** [comment]
是不是我命令打错了，试试`which -a node`和`which -a npm`

**Comment by Dakai** [comment]
还是一样的结果啊

**Comment by layerssss** [comment]
奇怪了， 那你能调用`node`命令吗？

**Comment by Dakai** [comment]
不行…command not found，奇怪了

**Comment by layerssss** [comment]
似乎找到邪恶的源头了，用这条命令试一试  `sudo /usr/local/bin/node /usr/local/bin/npm install lixian-portal -g`

**Comment by Dakai** [comment]
/usr/local/bin/node: command not found 
= =

**Comment by layerssss** [comment]
```
curl http://nodejs.org/dist/v0.10.15/node-v0.10.15.tar.gz | tar xz
cd node-v0.10.15 && make && make install
cd .. && rm -Rf node-v0.10.15
```

你这一步（就是之前告诉你的安装编译nodejs的命令）成功了吗？

**Comment by Dakai** [comment]
我怀疑最后没打make install，我再试试

**Comment by layerssss** [comment]
嗯，安装编译完后再调用`sudo /usr/local/bin/node /usr/local/bin/npm install lixian-portal -g`

**Comment by Dakai** [comment]
还是不行，我用sudo apt-get install node安装了，
which node -a返回 /usr/sbin/node 
which node -a返回 /usr/bin/npm
sudo /usr/local/bin/node /usr/local/bin/npm install lixian-portal -g
sudo /usr/sbin/node /usr/bin/npm install lixian-portal -g
都没有反应

**Comment by layerssss** [comment]
应该会比较慢吧，别木有反应呀

**Comment by layerssss** [comment]
木有反应是怎样？直接退出还是卡在那里？卡在那里的话等一等

**Comment by Dakai** [comment]
完全没反应，没有任何输出，就像按到回车一样

**Comment by Dakai** [comment]
真是不好意思，麻烦你那么久，估计是raspbmc的源版本有问题，实在不行我就命令行输入下载咯

**Comment by layerssss** [comment]
`No compatible version found: iced-coffee-script@'>1.4.0'`确实是因为 npm 版本过低导致的，不过新的npm安装不上俺却是就没遇到过了

**Comment by sicode** [comment]
![-003](https://cloud.githubusercontent.com/assets/3986116/6588345/4eee7d12-c7cb-11e4-8547-5a73fa22de2d.png)
現在我的安裝成功了，但是運行不起來。
