### ISSUE TITLE
你好，请教一下，这个webui是完全兼容xunlei-lixian的config配置文件的吗？

### ISSUE THREAD

**Issue by goxofy** [layerssss/lixian-portal#4]
比如我要定义output-dir或者下载工具，直接在config里加参数就可以了吗？

另外，node程序的启动端口怎么样重定义呢？3000已经被用啦！

**Comment by layerssss** [comment]
1. 这个 Webui 里面调用了 xunlei-lixian， 所以确实是兼容的
2. 定义PORT 变量即可， 例如
   
   ```
   export PORT=3001
   lixian-portal
   # 或者
   PORT=3001 lixian-portal
   ```

**Comment by goxofy** [comment]
你好，还有个问题，这个程序是将所有添加到迅雷离线的任务全部依次取回吗？不能指定某个？

**Comment by layerssss** [comment]
嗯， 自动全部取回，而且在取回完后删除 线上的。

**Comment by layerssss** [comment]
这样就方便一些嘛，平常不用管理， 只用进来添加新任务，然后过段时间去共享里找下载好的文件就可了 :trollface:

**Comment by goxofy** [comment]
我知道。。。但是我这个迅雷ID是20多个人在同时使用。。。。。。。。。。。。亲，你能不能搞一个可以指定取回的版本。。。

**Comment by layerssss** [comment]
那就直接用 xunlei-lixian 嘛， 俺这个是专门为单人账号设计的 :trollface:

**Comment by goxofy** [comment]
。。。。。

**Comment by layerssss** [comment]
@goxofy 可以以后考虑加入这个功能， 得思考一下具体细节

**Comment by goxofy** [comment]
嗯嗯，谢谢啦！！！

**Comment by shiny** [comment]
@layerssss  有时候是这样的，我的笔记本在别的地方用迅雷里下好了，不希望在公司也自动再下载一遍，更希望手动控制，或者提供相应选项。
